version: "3"
services:
  irisvpn-a:
    image: panchatattva/irisvpn.com
    ports: ["127.0.0.1:3000:3000"]
    volumes:
      - ./infrastructure/volume/production.sqlite3:/usr/src/irisvpn.com/db/production.sqlite3 
      - ./infrastructure/volume/master.key:/usr/src/irisvpn.com/config/master.key
      - ./infrastructure/volume/log:/usr/src/irisvpn.com/log
  irisvpn-b:
    image: panchatattva/irisvpn.com
    ports: ["127.0.0.1:3001:3000"]
    volumes:
      - ./infrastructure/volume/production.sqlite3:/usr/src/irisvpn.com/db/production.sqlite3 
      - ./infrastructure/volume/master.key:/usr/src/irisvpn.com/config/master.key
      - ./infrastructure/volume/log:/usr/src/irisvpn.com/log
  haproxy:
    image: haproxy:2.2
    volumes:
      - ./infrastructure/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
      - ./infrastructure/volume:/volume
    ports: ["4444:4444"]
